openaq:
  target: docker
  outputs:
    docker:
      type: postgres
      host: "{{ env_var('WAREHOUSE_DB_HOST') }}"
      port: "{{ env_var('WAREHOUSE_DB_PORT') | int }}"
      user: "{{ env_var('WAREHOUSE_DB_USER') }}"
      password: "{{ env_var('WAREHOUSE_DB_PASSWORD') }}"
      dbname: "{{ env_var('WAREHOUSE_DB_DB') }}"
      schema: "stg"   # default; models can override
      threads: 4
      keepalives_idle: 0
