{{  config(
        materialized='view'
) }}

with weather as (
    select event_id,
           event_type,
           source,
           office,
           grid_id,
           grid_x,
           grid_y,
           start_time,
           end_time,
           is_daytime,
           temperature,
           temperature_min,
           temperature_max,
           temperature_unit,
           temperature_trend,
           relative_humidity,
           relative_humidity_min,
           relative_humidity_max,
           relative_humidity_unit,
           dewpoint,
           dewpoint_min,
           dewpoint_max,
           dewpoint_unit,
           wind_speed,
           wind_speed_min,
           wind_speed_max,
           wind_speed_unit,
           wind_direction,
           wind_gust,
           wind_gust_min,
           wind_gust_max,
           wind_gust_unit,
           probability_of_precipitation,
           probability_of_precipitation_min,
           probability_of_precipitation_max,
           probability_of_precipitation_unit,
           short_forecast,
           detailed_forecast,
           ingested_at,
           last_updated_at
    from {{ ref('stg_weather_hourly_forecast_by_location') }}
),
air AS (
    SELECT event_id,
           locations_id,
           sensors_id,
           datetime_utc,
           value,
           source,
           ingested_at,
           rn
    FROM (
        SELECT event_id,
               locations_id,
               sensors_id,
               datetime_utc,
               value,
               source,
               ingested_at,
               row_number() OVER (ORDER BY datetime_utc DESC) AS rn
          FROM {{ ref('stg_openaq_measurements_by_location') }}
         ORDER BY datetime_utc DESC
     ) as w
     WHERE rn = 1
)
SELECT weather.event_id AS wx_event_id,
       event_type AS wx_event_type,
       weather.source AS wx_source,
       office AS wx_office,
       grid_id AS wx_grid_id,
       grid_x AS wx_grid_x,
       grid_y AS wx_grid_y,
       start_time wx_start_time,
       end_time wx_end_time,
       is_daytime AS wx_is_daytime,
       temperature AS wx_temperature,
       temperature_min AS wx_temperature_min,
       temperature_max AS wx_temperature_max,
       temperature_unit AS wx_temperature_unit,
       temperature_trend AS wx_temperature_trend,
       relative_humidity AS wx_relative_humidity,
       relative_humidity_min AS wx_relative_humidity_min,
       relative_humidity_max AS wx_relative_humidity_max,
       relative_humidity_unit AS wx_relative_humidity_unit,
       dewpoint AS wx_dewpoint,
       dewpoint_min AS wx_dewpoint_min,
       dewpoint_max AS wx_dewpoint_max,
       dewpoint_unit AS wx_dewpoint_unit,
       wind_speed AS wx_wind_speed,
       wind_speed_min AS wx_wind_speed_min,
       wind_speed_max AS wx_wind_speed_max,
       wind_speed_unit AS wx_wind_speed_unit,
       wind_direction AS wx_wind_direction,
       wind_gust AS wx_wind_gust,
       wind_gust_min AS wx_wind_gust_min,
       wind_gust_max AS wx_wind_gust_max,
       wind_gust_unit AS wx_wind_gust_unit,
       probability_of_precipitation AS wx_probability_of_precipitation,
       probability_of_precipitation_min AS wx_probability_of_precipitation_min,
       probability_of_precipitation_max AS wx_probability_of_precipitation_max,
       probability_of_precipitation_unit AS wx_probability_of_precipitation_unit,
       short_forecast AS wx_short_forecast,
       detailed_forecast AS wx_detailed_forecast,
       weather.ingested_at AS wx_ingested_at,
       last_updated_at AS wx_last_updated_at,
       air.event_id AS aq_event_id,
       locations_id AS aq_locations_id,
       sensors_id AS aq_sensors_id,
       datetime_utc AS aq_datetime_utc,
       value AS aq_sensor_value,
       air.source AS aq_source,
       air.ingested_at AS aq_ingested_at,
       abs(extract(epoch FROM (weather.start_time - air.datetime_utc))) AS aq_wx_abs_time_diff

  FROM weather
  CROSS JOIN air
  ORDER BY aq_wx_abs_time_diff ASC
